-- liquibase formatted sql

-- changeset crfa-metadata-service-reloaded:1

CREATE SEQUENCE IF NOT EXISTS example_seq;

CREATE TABLE IF NOT EXISTS example (
	id int GENERATED BY DEFAULT AS SEQUENCE example_seq PRIMARY KEY,
	firstname varchar(50) not null,
	lastname varchar(50) not null,
	state char(2)
)

-- rollback DROP TABLE "example_table" CASCADE;

GRANT SELECT, INSERT, UPDATE, DELETE ON example TO sa;
